"""Generated by packaging/generate_ui_tokens.py; do not edit."""

SOURCE_SHA256 = 'd6f2a2bcaeb16a88d0a1f76fd501bfdffd8e15ddf1cc25093f6036e3fa852d47'

COLORS = {'accent': '#087E72',
 'accent_hover': '#06675F',
 'accent_soft': '#DCEFEB',
 'app_bg': '#F5F7F8',
 'border': '#718089',
 'border_strong': '#52616A',
 'caution_bg': '#FFF4D6',
 'caution_fg': '#7A4E00',
 'diagram_backbone': '#9AA4AD',
 'diagram_base_a': '#2CA02C',
 'diagram_base_c': '#1F77B4',
 'diagram_base_fallback': '#333333',
 'diagram_base_g': '#E08214',
 'diagram_base_n': '#7F7F7F',
 'diagram_base_t': '#D62728',
 'diagram_bond_neutral': '#7B8794',
 'diagram_caution_accent': '#B7791F',
 'diagram_caution_dark': '#6F4E00',
 'diagram_muted': '#59636E',
 'diagram_node_outline': '#D0D7DE',
 'diagram_ok_accent': '#2F855A',
 'diagram_ok_dark': '#1F5F3D',
 'diagram_problem_dark': '#7A271A',
 'diagram_risk_zone': '#FFF2BF',
 'diagram_text': '#2F3437',
 'diagram_unclassified_bg': '#F2F4F5',
 'diagram_unclassified_dark': '#3F4850',
 'focus': '#087E72',
 'ok_bg': '#E7F5EC',
 'ok_fg': '#18794E',
 'on_accent': '#FFFFFF',
 'problem_active': '#FBD5D5',
 'problem_bg': '#FDE8E8',
 'problem_fg': '#B42318',
 'selected': '#DCEFEB',
 'surface': '#FFFFFF',
 'surface_muted': '#EDF1F2',
 'surface_subtle': '#F8FAFB',
 'text': '#172229',
 'text_muted': '#52616A'}

SPACING = {'lg': 16, 'md': 12, 'sm': 8, 'xl': 24, 'xs': 4, 'xxs': 2}

FONT_FAMILIES = {'body': 'Segoe UI', 'mono': 'Cascadia Mono'}

DIMENSIONS = {'matrix_header_height': 44, 'matrix_label_width': 152, 'sidebar_width': 368}

COMFORTABLE = {'body_size': 9,
 'control_pad_y': 7,
 'matrix_cell_h': 36,
 'matrix_cell_w': 96,
 'mono_size': 10,
 'rowheight': 24}
