"""Generate import-only Tk tokens from the authoritative design-token JSON."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from pprint import pformat
import sys


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "tokens" / "mbuprime_structlab.tokens.json"
DEFAULT_OUTPUT = ROOT / "gui_tokens_generated.py"


def _values(group: dict) -> dict:
    return {
        key.replace("-", "_"): value["$value"]
        for key, value in group.items()
        if not key.startswith("$")
    }


def _integer_values(group: dict) -> dict[str, int]:
    return {
        key.replace("-", "_"): int(value["$value"].removesuffix("px"))
        for key, value in group.items()
        if not key.startswith("$")
    }


def render(source: Path) -> bytes:
    raw = source.read_bytes()
    data = json.loads(raw.decode("utf-8"))
    colors = _values(data["color"])
    spacing = _integer_values(data["spacing"])
    fonts = {
        key.replace("-", "_"): str(value["$value"])
        for key, value in data["typography"].items()
    }
    dimensions = {
        key.replace("-", "_"): int(value)
        for key, value in data["dimensions"].items()
    }
    comfortable = {
        key.replace("-", "_"): int(value)
        for key, value in data["comfortable"].items()
    }
    for color in colors.values():
        if not isinstance(color, str) or len(color) != 7 or color[0] != "#":
            raise ValueError(f"invalid six-digit color token: {color!r}")
    digest = hashlib.sha256(raw).hexdigest()
    values = {
        "SOURCE_SHA256": digest,
        "COLORS": colors,
        "SPACING": spacing,
        "FONT_FAMILIES": fonts,
        "DIMENSIONS": dimensions,
        "COMFORTABLE": comfortable,
    }
    lines = [
        '"""Generated by packaging/generate_ui_tokens.py; do not edit."""',
        "",
    ]
    for name, value in values.items():
        lines.append(f"{name} = {pformat(value, sort_dicts=True, width=88)}")
        lines.append("")
    return ("\n".join(lines).rstrip() + "\n").encode("utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    expected = render(args.input.resolve())
    output = args.output.resolve()
    if args.check:
        if not output.is_file() or output.read_bytes() != expected:
            print(f"stale generated UI tokens: {output}", file=sys.stderr)
            return 1
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
